apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: certifyapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ${ECR_REGISTRY}/certifyapp/payment-service:latest
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: certifyapp-config
            - secretRef:
                name: certifyapp-secrets
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: certifyapp
spec:
  selector:
    app: payment-service
  ports:
    - port: 8086
      targetPort: 8086
