apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: certifyapp-staging
resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../user-service-deployment.yaml
  - ../../auth-service-deployment.yaml
  - ../../api-gateway-deployment.yaml
  - ../../ingress.yaml
namePrefix: staging-
